from django.db import models

# Create your models here.
class Game(models.Model):
    player1 = models.CharField(max_length=64)
    player2 = models.CharField(max_length=64)
    pgn = models.TextField()
    endComment = models.CharField(max_length=64)

class Board(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name="moves")
    check = models.BooleanField()

    a1 = models.CharField(max_length=32)
    a2 = models.CharField(max_length=32)
    a3 = models.CharField(max_length=32)
    a4 = models.CharField(max_length=32)
    a5 = models.CharField(max_length=32)
    a6 = models.CharField(max_length=32)
    a7 = models.CharField(max_length=32)
    a8 = models.CharField(max_length=32)

    b1 = models.CharField(max_length=32)
    b2 = models.CharField(max_length=32)
    b3 = models.CharField(max_length=32)
    b4 = models.CharField(max_length=32)
    b5 = models.CharField(max_length=32)
    b6 = models.CharField(max_length=32)
    b7 = models.CharField(max_length=32)
    b8 = models.CharField(max_length=32)

    c1 = models.CharField(max_length=32)
    c2 = models.CharField(max_length=32)
    c3 = models.CharField(max_length=32)
    c4 = models.CharField(max_length=32)
    c5 = models.CharField(max_length=32)
    c6 = models.CharField(max_length=32)
    c7 = models.CharField(max_length=32)
    c8 = models.CharField(max_length=32)

    d1 = models.CharField(max_length=32)
    d2 = models.CharField(max_length=32)
    d3 = models.CharField(max_length=32)
    d4 = models.CharField(max_length=32)
    d5 = models.CharField(max_length=32)
    d6 = models.CharField(max_length=32)
    d7 = models.CharField(max_length=32)
    d8 = models.CharField(max_length=32)

    e1 = models.CharField(max_length=32)
    e2 = models.CharField(max_length=32)
    e3 = models.CharField(max_length=32)
    e4 = models.CharField(max_length=32)
    e5 = models.CharField(max_length=32)
    e6 = models.CharField(max_length=32)
    e7 = models.CharField(max_length=32)
    e8 = models.CharField(max_length=32)

    f1 = models.CharField(max_length=32)
    f2 = models.CharField(max_length=32)
    f3 = models.CharField(max_length=32)
    f4 = models.CharField(max_length=32)
    f5 = models.CharField(max_length=32)
    f6 = models.CharField(max_length=32)
    f7 = models.CharField(max_length=32)
    f8 = models.CharField(max_length=32)

    g1 = models.CharField(max_length=32)
    g2 = models.CharField(max_length=32)
    g3 = models.CharField(max_length=32)
    g4 = models.CharField(max_length=32)
    g5 = models.CharField(max_length=32)
    g6 = models.CharField(max_length=32)
    g7 = models.CharField(max_length=32)
    g8 = models.CharField(max_length=32)

    h1 = models.CharField(max_length=32)
    h2 = models.CharField(max_length=32)
    h3 = models.CharField(max_length=32)
    h4 = models.CharField(max_length=32)
    h5 = models.CharField(max_length=32)
    h6 = models.CharField(max_length=32)
    h7 = models.CharField(max_length=32)
    h8 = models.CharField(max_length=32)
