# Generated by Django 3.0.6 on 2021-02-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=64)),
                ('player2', models.CharField(max_length=64)),
                ('pgn', models.TextField()),
                ('endComment', models.CharField(max_length=64)),
            ],
        ),
    ]
